export const projectsData = {
  title: "Projects",
  bannedImg: "/imgs/page-head/banner-projects.jpg",
  categories: [
    { label: "ELECTRO MECHANICAL", filter: ".ele-mech" },
    { label: "PLATE WORK", filter: ".plt-wrk" },
    { label: "SEMI-TRAILERS", filter: ".sem-tra" },
    { label: "STEEL STRUCTURE", filter: ".stl-str" },
    { label: "TRANSMISSION TOWERS", filter: ".trans-towrs" },
  ],
  projects: [
    {
      category: "ele-mech",
      image: "/imgs/projects/elec-tech/ele-mech-1.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "ele-mech",
      image: "/imgs/projects/elec-tech/ele-mech-2.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "ele-mech",
      image: "/imgs/projects/elec-tech/ele-mech-3.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "ele-mech",
      image: "/imgs/projects/elec-tech/ele-mech-4.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "ele-mech",
      image: "/imgs/projects/elec-tech/ele-mech-5.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "ele-mech",
      image: "/imgs/projects/elec-tech/ele-mech-6.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "ele-mech",
      image: "/imgs/projects/elec-tech/ele-mech-7.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "ele-mech",
      image: "/imgs/projects/elec-tech/ele-mech-8.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "ele-mech",
      image: "/imgs/projects/elec-tech/ele-mech-9.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "plt-wrk",
      image: "/imgs/projects/plt-wrk/plt-wrk-1.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "plt-wrk",
      image: "/imgs/projects/plt-wrk/plt-wrk-2.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-1.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-2.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-3.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-4.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-5.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-6.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-7.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-8.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-9.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "sem-tra",
      image: "/imgs/projects/sem-tra/sem-tra-10.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-1.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-2.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-3.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-4.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-5.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-6.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-7.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-8.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-9.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-10.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-11.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-12.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-13.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-14.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-15.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-16.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-17.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-18.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-19.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-20.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-21.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-22.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-23.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-24.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-25.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-26.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-27.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-28.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-29.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-30.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-31.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "stl-str",
      image: "/imgs/projects/stl-str/stl-str-32.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "trans-towrs",
      image: "/imgs/projects/trans-towrs/trans-towrs-1.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "trans-towrs",
      image: "/imgs/projects/trans-towrs/trans-towrs-2.jpeg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "trans-towrs",
      image: "/imgs/projects/trans-towrs/trans-towrs-3.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "trans-towrs",
      image: "/imgs/projects/trans-towrs/trans-towrs-4.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "trans-towrs",
      image: "/imgs/projects/trans-towrs/trans-towrs-5.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
    {
      category: "trans-towrs",
      image: "/imgs/projects/trans-towrs/trans-towrs-6.jpg",
      title: "ELECTRO MECHANICAL",
      description: "INSTALLATION OF STRUCTURAL STEEL",
      link: `${process.env.NEXT_PUBLIC_URI}/en/projects/installation-of-structural-steel/`,
    },
  ],
};